<?php
namespace Database\Seeders;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['category' => 'Chips', 'product_name' => 'Chips', 'item_code' => 'chips', 'selling_price' => 35.00],
            ['category' => 'ICE CREAMS', 'product_name' => 'Icecream', 'item_code' => 'icecream', 'selling_price' => 40.00],
            ['category' => 'Chocolates', 'product_name' => 'V Chocolate', 'item_code' => '0101', 'selling_price' => 39.00],
            ['category' => 'Egg Puffs', 'product_name' => 'Egg Puff', 'item_code' => '6', 'selling_price' => 32.00],
            ['category' => 'COOL DRINKS', 'product_name' => 'Cool Drinks', 'item_code' => 'cool drinks', 'selling_price' => 28.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Almond Dry Cake 200gms', 'item_code' => '4038', 'selling_price' => 99.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Dilpasand[450gms]', 'item_code' => '167', 'selling_price' => 80.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Vanilla Cream Sponge Slices 250gms', 'item_code' => '2076', 'selling_price' => 129.00],
            ['category' => 'Veg Bites', 'product_name' => 'Veg Nuggets', 'item_code' => 'veg nuggets', 'selling_price' => 119.00],
            ['category' => 'Breads', 'product_name' => 'Milk Bread 900gms', 'item_code' => '170', 'selling_price' => 99.00],
            ['category' => 'Veg Puffs', 'product_name' => 'Veg Puff', 'item_code' => '1', 'selling_price' => 30.00],
            ['category' => 'Samosa', 'product_name' => 'Chicken Samosa', 'item_code' => '24', 'selling_price' => 35.00],
            ['category' => 'Chicken Puffs', 'product_name' => 'Butter Chicken Puff', 'item_code' => '17', 'selling_price' => 75.00],
            ['category' => 'Non-Veg Rolls', 'product_name' => 'Chicken Roll', 'item_code' => '27', 'selling_price' => 49.00],
            ['category' => 'Veg Puffs', 'product_name' => 'Paneer Puff', 'item_code' => '2', 'selling_price' => 42.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Tie Biscuits Box', 'item_code' => '2039', 'selling_price' => 100.00],
            ['category' => 'miyapur raw items', 'product_name' => 'CARAT (COVERLUX DARK CHOCOLATES) /KG', 'item_code' => 'CARAT (COVERLUX DARK', 'selling_price' => 250.00],
            ['category' => 'Breads', 'product_name' => 'Brown Bread (300 Gms)', 'item_code' => '171', 'selling_price' => 55.00],
            ['category' => 'Breads', 'product_name' => 'Shirmal Bun', 'item_code' => '175', 'selling_price' => 40.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Cup Cake 6pc', 'item_code' => '155', 'selling_price' => 99.00],
            ['category' => 'Plum Cake', 'product_name' => 'Plum Cake (50 Gms)', 'item_code' => '221', 'selling_price' => 30.00],
            ['category' => 'Breads', 'product_name' => 'Burger Buns (Mini)', 'item_code' => '190', 'selling_price' => 29.00],
            ['category' => 'Breads', 'product_name' => 'Burger Buns (Medium)', 'item_code' => '190', 'selling_price' => 35.00],
            ['category' => 'Chicken Puffs', 'product_name' => 'Chicken Puff', 'item_code' => '14', 'selling_price' => 45.00],
            ['category' => 'Chicken Puffs', 'product_name' => 'Chicken Cheese Puff', 'item_code' => '16', 'selling_price' => 50.00],
            ['category' => 'Chicken Puffs', 'product_name' => 'Ginger Chicken Puff', 'item_code' => '15', 'selling_price' => 50.00],
            ['category' => 'Egg Puffs', 'product_name' => 'Double Egg Puff', 'item_code' => '7', 'selling_price' => 38.00],
            ['category' => 'Veg Puffs', 'product_name' => 'Palak Paneer Puff', 'item_code' => '3', 'selling_price' => 42.00],
            ['category' => 'Veg Puffs', 'product_name' => 'Veg Cheese Puff', 'item_code' => '13', 'selling_price' => 49.00],
            ['category' => 'Samosa', 'product_name' => 'Veg Samosa', 'item_code' => '23', 'selling_price' => 25.00],
            ['category' => 'Samosa', 'product_name' => 'Paneer Samosa', 'item_code' => '26', 'selling_price' => 30.00],
            ['category' => 'Non-Veg Bites', 'product_name' => 'Chicken 65 Cup', 'item_code' => '65', 'selling_price' => 60.00],
            ['category' => 'Breads', 'product_name' => 'Tea Bun', 'item_code' => '4056', 'selling_price' => 20.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Honey Almond Pastry', 'item_code' => '267', 'selling_price' => 99.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Vanilla Cup Cake', 'item_code' => '182', 'selling_price' => 60.00],
            ['category' => 'Birthday Items', 'product_name' => 'Heart Shape Balloons', 'item_code' => '3047', 'selling_price' => 69.00],
            ['category' => 'COOL DRINKS', 'product_name' => 'Thums Up', 'item_code' => '8901764042911', 'selling_price' => 20.00],
            ['category' => 'Breads', 'product_name' => 'Milk Breads 600gms', 'item_code' => '169', 'selling_price' => 75.00],
            ['category' => 'Breads', 'product_name' => 'Fruit Bread', 'item_code' => '173', 'selling_price' => 35.00],
            ['category' => 'Birthday Items', 'product_name' => 'Sparkle Candle', 'item_code' => '501', 'selling_price' => 30.00],
            ['category' => 'Birthday Items', 'product_name' => 'Snow Spray', 'item_code' => '3035', 'selling_price' => 65.00],
            ['category' => 'Joy Cakes 700gms', 'product_name' => 'Choco Joy Cake (eggless) 700gms', 'item_code' => '248', 'selling_price' => 569.00],
            ['category' => 'Breads', 'product_name' => 'Dil-pasand (1 Pc)', 'item_code' => '179', 'selling_price' => 30.00],
            ['category' => 'Breads', 'product_name' => 'Dilkush', 'item_code' => '176', 'selling_price' => 29.00],
            ['category' => 'Chocolates', 'product_name' => 'Gourmet Wafer 90mrp', 'item_code' => '3008', 'selling_price' => 90.00],
            ['category' => 'Non-Veg Pizza', 'product_name' => 'Chicken Hot Mix Cheese Pizza (Mini)', 'item_code' => 'chicken hot mix chee', 'selling_price' => 145.00],
            ['category' => 'Breads', 'product_name' => 'Maska Bun', 'item_code' => '120', 'selling_price' => 35.00],
            ['category' => 'Breads', 'product_name' => 'Cream Bun', 'item_code' => '177', 'selling_price' => 33.00],
            ['category' => 'Birthday Items', 'product_name' => 'Gold Candles', 'item_code' => '3027', 'selling_price' => 50.00],
            ['category' => 'Joy Cakes 500 gms', 'product_name' => 'Gulabjamun Cake 500gms', 'item_code' => 'gulabjamun cake 500g', 'selling_price' => 649.00],
            ['category' => 'Birthday Items', 'product_name' => 'Birthday Cap 55rs', 'item_code' => '3076', 'selling_price' => 55.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Gulab Jamun Pastry', 'item_code' => '275', 'selling_price' => 109.00],
            ['category' => 'Birthday Items', 'product_name' => 'Ribbon Spray', 'item_code' => '3038', 'selling_price' => 70.00],
            ['category' => 'Chocolate Pastry', 'product_name' => 'Choco Chips Pastry', 'item_code' => '291', 'selling_price' => 99.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Pista Pastry', 'item_code' => '260', 'selling_price' => 99.00],
            ['category' => 'Chocolate Pastry', 'product_name' => 'Butter Almond Pastry', 'item_code' => '293', 'selling_price' => 99.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Banana Cake 200gms', 'item_code' => '163', 'selling_price' => 135.00],
            ['category' => 'Joy Cakes 500 gms', 'product_name' => 'Chocolate Joycake 500gms', 'item_code' => 'chocolate joycake 50', 'selling_price' => 479.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Vanilla Sponge Cake (250 Gms)', 'item_code' => '162', 'selling_price' => 185.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Dilpasand 1kg', 'item_code' => '180', 'selling_price' => 120.00],
            ['category' => 'Chocolate Pastry', 'product_name' => 'German Chocolate Pastry', 'item_code' => '295', 'selling_price' => 99.00],
            ['category' => 'Breads', 'product_name' => 'Milk Bread 300gms', 'item_code' => '168', 'selling_price' => 55.00],
            ['category' => 'Birthday Items', 'product_name' => 'Ola Birthday Caps', 'item_code' => '3142', 'selling_price' => 25.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Ghee Cake 200gms', 'item_code' => '161', 'selling_price' => 119.00],
            ['category' => 'Joy Cakes 700gms', 'product_name' => 'Joy Cake 700gms', 'item_code' => '247', 'selling_price' => 529.00],
            ['category' => 'Chocolates', 'product_name' => 'Rainbow Jopadi', 'item_code' => '3025', 'selling_price' => 100.00],
            ['category' => 'Joy Cakes 500 gms', 'product_name' => 'Buttersctoch Cake 500gms', 'item_code' => 'buttersctoch 500gms', 'selling_price' => 429.00],
            ['category' => 'Veg Bites', 'product_name' => 'Salted French Fries (Mini)', 'item_code' => '54', 'selling_price' => 116.00],
            ['category' => 'Chocolate Pastry', 'product_name' => 'Black Forest Pastry', 'item_code' => '289', 'selling_price' => 145.00],
            ['category' => 'Breads', 'product_name' => 'Pav Bhaji Bread', 'item_code' => '174', 'selling_price' => 40.00],
            ['category' => 'Basic Pastries', 'product_name' => 'Butterscotch Pastry', 'item_code' => '258', 'selling_price' => 79.00],
            ['category' => 'Breads', 'product_name' => 'Fine Biscuit 600gms', 'item_code' => '205', 'selling_price' => 110.00],
            ['category' => 'Birthday Items', 'product_name' => 'Party Popp(m)', 'item_code' => '3039', 'selling_price' => 90.00],
            ['category' => 'Regular Cakes  1kg', 'product_name' => 'Butterscotch Cake 1kg', 'item_code' => '333', 'selling_price' => 750.00],
            ['category' => 'Chocolate Pastry', 'product_name' => 'Vanilla Chocolate Pastry', 'item_code' => '299', 'selling_price' => 99.00],
            ['category' => 'Regular Cakes  1kg', 'product_name' => 'Black Forest Cake 1kg', 'item_code' => '363', 'selling_price' => 749.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Blue Berry Dry Cake', 'item_code' => '4048', 'selling_price' => 99.00],
            ['category' => 'Veg Bites', 'product_name' => 'Veg Mushroom Roll', 'item_code' => '22', 'selling_price' => 30.00],
            ['category' => 'Non-Veg Rolls', 'product_name' => 'Chicken Cheese Roll', 'item_code' => '40', 'selling_price' => 69.00],
            ['category' => 'Breads', 'product_name' => 'Choco Muffins', 'item_code' => '185', 'selling_price' => 109.00],
            ['category' => 'Basic Pastries', 'product_name' => 'Pineapple Pastry', 'item_code' => '255', 'selling_price' => 79.00],
            ['category' => 'Chocolate Pastry', 'product_name' => 'Donut', 'item_code' => '300', 'selling_price' => 145.00],
            ['category' => 'Basic Pastries', 'product_name' => 'Vanilla Pastry', 'item_code' => '256', 'selling_price' => 79.00],
            ['category' => 'Regular Cakes  1kg', 'product_name' => 'Fancy Cake 1kg', 'item_code' => 'fancy cake 1kg', 'selling_price' => 1000.00],
            ['category' => 'Butter Cream Cakes', 'product_name' => 'Buttersctoch Cake (Buttercream) (500 Gms)', 'item_code' => 'buttersctoch cake 50', 'selling_price' => 300.00],
            ['category' => 'Non-Veg Burgers', 'product_name' => 'Chicken Burger (Medium)', 'item_code' => '92', 'selling_price' => 168.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Pine Apple Dry Cake 200gms', 'item_code' => '4039', 'selling_price' => 99.00],
            ['category' => 'Veg Rolls', 'product_name' => 'Veg Roll', 'item_code' => '29', 'selling_price' => 40.00],
            ['category' => 'miyapur raw items', 'product_name' => 'Vanilla Sponge (maida)', 'item_code' => 'vanilla sponge (maid', 'selling_price' => 140.00],
            ['category' => 'Veg Rolls', 'product_name' => 'Paneer Roll', 'item_code' => '20', 'selling_price' => 49.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Swiss Roll [250grms]', 'item_code' => '3199', 'selling_price' => 120.00],
            ['category' => 'Non-Veg Pizza', 'product_name' => 'Chicken Mix Cheese Pizza (Mini)', 'item_code' => 'chicken mix cheese p', 'selling_price' => 145.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Kaari Biscuits Box', 'item_code' => '4005', 'selling_price' => 100.00],
            ['category' => 'RETAIL ITEM', 'product_name' => 'Jelly 100gms', 'item_code' => '20230010', 'selling_price' => 50.00],
            ['category' => 'Basic Pastries', 'product_name' => 'Panda Pastry', 'item_code' => '273', 'selling_price' => 99.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Almond Sticks 250gms', 'item_code' => '2034', 'selling_price' => 179.00],
            ['category' => 'Breads', 'product_name' => 'No Maida Bread 300gm', 'item_code' => null, 'selling_price' => 65.00],
            ['category' => 'Veg Pizza', 'product_name' => 'Salted French Fries (Large)', 'item_code' => null, 'selling_price' => 183.00],
            ['category' => 'Non-Veg Rolls', 'product_name' => 'Chicken Hot Dog (cheese roll)', 'item_code' => null, 'selling_price' => 79.00],
            ['category' => 'Non-Veg Rolls', 'product_name' => 'Chicken Spring Roll', 'item_code' => null, 'selling_price' => 85.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Ferraro Chocolate Pastry', 'item_code' => null, 'selling_price' => 129.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Butter Scotch Cookies-[jaggery] 250gms', 'item_code' => null, 'selling_price' => 150.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Multigrain Cookies - [Jaggery] 300gms', 'item_code' => null, 'selling_price' => 180.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Fruit Cookies (jaggery) 300gms', 'item_code' => null, 'selling_price' => 180.00],
            ['category' => 'RETAIL ITEM', 'product_name' => 'Till Laddus 200gms', 'item_code' => null, 'selling_price' => 75.00],
            ['category' => 'Breads', 'product_name' => 'No Maida Bread 600gm', 'item_code' => null, 'selling_price' => 85.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Brownie Boxes 200gms', 'item_code' => null, 'selling_price' => 130.00],
            ['category' => 'Breads', 'product_name' => 'Burger Roll', 'item_code' => null, 'selling_price' => 15.00],
            ['category' => 'Breads', 'product_name' => 'Dinner Roll', 'item_code' => null, 'selling_price' => 15.00],
            ['category' => 'Dry Cakes', 'product_name' => 'vanilla moulds 290gm', 'item_code' => null, 'selling_price' => 55.00],
            ['category' => 'Dry Cakes', 'product_name' => 'chocolate moulds 520gm', 'item_code' => null, 'selling_price' => 63.80],
            ['category' => 'Dry Cakes', 'product_name' => 'Fruit Cake (300gms', 'item_code' => '165', 'selling_price' => 140.00],
            ['category' => 'Breads', 'product_name' => 'Pizza Base (Mini)', 'item_code' => null, 'selling_price' => 30.00],
            ['category' => 'Veg Rolls', 'product_name' => 'Veg Spring Roll (cheese roll)', 'item_code' => null, 'selling_price' => 69.00],
            ['category' => 'RETAIL ITEM', 'product_name' => 'Truffles 2 D/H', 'item_code' => null, 'selling_price' => 60.00],
            ['category' => 'Veg Rolls', 'product_name' => 'Paneer Cheese Roll (cheese roll)', 'item_code' => null, 'selling_price' => 69.00],
            ['category' => 'Veg Pizza', 'product_name' => 'Extra Cheese', 'item_code' => null, 'selling_price' => 20.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Dark Fantacy Pastry', 'item_code' => null, 'selling_price' => 129.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Kaju Cookies-[jaggery] 300gms', 'item_code' => null, 'selling_price' => 165.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Redvelvet Pastry', 'item_code' => null, 'selling_price' => 129.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Apple Pastry', 'item_code' => null, 'selling_price' => 115.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Dark Choco Chip Cookies 250gms', 'item_code' => null, 'selling_price' => 180.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Ragi Cookies-[jaggery] 300gms', 'item_code' => null, 'selling_price' => 165.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Regular Fruit Joy Cake 700gms', 'item_code' => null, 'selling_price' => 599.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Rasmalai Pastry', 'item_code' => null, 'selling_price' => 129.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Redvelvet Cake 500gms', 'item_code' => null, 'selling_price' => 469.00],
            ['category' => 'Premium Pastries', 'product_name' => 'Choco Truffle Pastry', 'item_code' => null, 'selling_price' => 115.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Rasmalai Joy Cake 500gms', 'item_code' => null, 'selling_price' => 669.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Chocolate Cake 2 Step', 'item_code' => null, 'selling_price' => 1600.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Blackforest Cake 2step', 'item_code' => null, 'selling_price' => 1600.00],
            ['category' => 'Petpooja Items', 'product_name' => 'Choco Bliss(heart)', 'item_code' => null, 'selling_price' => 160.00],
            ['category' => 'Veg Pizza', 'product_name' => 'Masala French Fries (Mini)', 'item_code' => null, 'selling_price' => 99.00],
            ['category' => 'Veg Pizza', 'product_name' => 'Veg Hot Mix Cheese Pizza (Large)', 'item_code' => null, 'selling_price' => 415.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Sugar Less Cookies 300gms', 'item_code' => null, 'selling_price' => 150.00],
            ['category' => 'Birthday Items', 'product_name' => 'Ballons Pump', 'item_code' => null, 'selling_price' => 60.00],
            ['category' => 'Birthday Items', 'product_name' => 'Number Foil Balloons', 'item_code' => null, 'selling_price' => 59.00],
            ['category' => 'RETAIL ITEM', 'product_name' => 'Polo Ring 100 Gms', 'item_code' => null, 'selling_price' => 40.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Chocolate Kaju Cookies 300gms', 'item_code' => null, 'selling_price' => 180.00],
            ['category' => 'Non-Veg Sandwich', 'product_name' => 'Chicken Classic Sandwich', 'item_code' => null, 'selling_price' => 130.00],
            ['category' => 'Birthday Items', 'product_name' => 'V Banner', 'item_code' => null, 'selling_price' => 70.00],
            ['category' => 'Petpooja Items', 'product_name' => 'Coconut Badam-[jaggery] 300gms', 'item_code' => null, 'selling_price' => 165.00],
            ['category' => 'Non-Veg Rolls', 'product_name' => 'Chicken Cheese Roll (cheese roll)', 'item_code' => null, 'selling_price' => 79.00],
            ['category' => 'Birthday Items', 'product_name' => 'Paper Plates Packet', 'item_code' => null, 'selling_price' => 25.00],
            ['category' => 'Birthday Items', 'product_name' => 'Single Color Balloons', 'item_code' => null, 'selling_price' => 60.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Corn Flakes Cookies 250gms', 'item_code' => null, 'selling_price' => 180.00],
            ['category' => 'Veg Pizza', 'product_name' => 'Chicken Tikka Delight Pizza (Large)', 'item_code' => null, 'selling_price' => 391.00],
            ['category' => 'Petpooja Items', 'product_name' => 'Non Veg Classic Duo', 'item_code' => null, 'selling_price' => 224.00],
            ['category' => 'Non-Veg Burgers', 'product_name' => 'Chicken Classic Burger (Mini)', 'item_code' => null, 'selling_price' => 145.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Osmania Biscuits 300gms', 'item_code' => null, 'selling_price' => 150.00],
            ['category' => 'Veg Rolls', 'product_name' => 'Chicken Hot Dog', 'item_code' => null, 'selling_price' => 104.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Blue Berry Dry Cakee', 'item_code' => null, 'selling_price' => 119.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Carrot Dry Cake', 'item_code' => null, 'selling_price' => 119.00],
            ['category' => 'RETAIL ITEM', 'product_name' => 'BUTTERSCTOCH CHIKKI/KG', 'item_code' => null, 'selling_price' => 350.00],
            ['category' => 'Dry Cakes', 'product_name' => 'Cake Book Orders', 'item_code' => null, 'selling_price' => 1706.25],
            ['category' => 'Breads', 'product_name' => 'Pizza Base (Medium)', 'item_code' => null, 'selling_price' => 35.00],
            ['category' => 'Petpooja Items', 'product_name' => 'Toes (200gms)', 'item_code' => null, 'selling_price' => 110.00],
            ['category' => 'Veg Pizza', 'product_name' => 'Chicken Mix Cheese Pizza (Large)', 'item_code' => null, 'selling_price' => 370.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Chand Cookies 300gms', 'item_code' => null, 'selling_price' => 180.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Coconut Kaju Cookies-[jaggery] 250gms', 'item_code' => null, 'selling_price' => 139.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Pista Sticks 250gms', 'item_code' => null, 'selling_price' => 200.00],
            ['category' => 'Petpooja Items', 'product_name' => 'Honey Corn Flakes-[Jaggery] 300gms', 'item_code' => null, 'selling_price' => 215.00],
            ['category' => 'BISCUITS BOXES', 'product_name' => 'Pista Delight Cookies 250gms', 'item_code' => null, 'selling_price' => 200.00],
            ['category' => 'Dry Cakes', 'product_name' => 'vanilla moulds 520gm', 'item_code' => null, 'selling_price' => 95.00],
            ['category' => 'Dry Cakes', 'product_name' => 'chocolate moulds 290gm', 'item_code' => null, 'selling_price' => 31.90],
            ['category' => 'Veg Pizza', 'product_name' => 'Pizza Chicken', 'item_code' => null, 'selling_price' => 390.00],
            ['category' => 'miyapur raw items', 'product_name' => 'BUTTERCREAM/KG', 'item_code' => null, 'selling_price' => 250.00],
            ['category' => 'Veg Rolls', 'product_name' => 'Veg Spring Roll', 'item_code' => null, 'selling_price' => 80.00],
            ['category' => 'Birthday Items', 'product_name' => 'Sash', 'item_code' => null, 'selling_price' => 75.00],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['product_name' => $product['product_name']],
                [
                    'category' => $product['category'],
                    'item_code' => $product['item_code'],
                    'cost_price' => 0,
                    'selling_price' => $product['selling_price'],
                    'shelf_life_days' => 0,
                    'reorder_level' => 0,
                    'status' => 'active',
                ]
            );
        }
    }
}